### ISSUE TITLE
TypeError: UNet2DConditionModel.forward() got an unexpected keyword argument 'objs'

### ISSUE THREAD

**Issue by fhlt** [OPPO-Mente-Lab/attention-mask-control#2]

**Comment by Glanceyes** [comment]
Same issue

**Comment by Wrch1994** [comment]
Hello, we have fixed some bugs in the training code in the latest commit. After testing, this version of the code can be used for training normally. Please pull the latest code in the master branch and set up the environment according to the updated environment.yaml to prevent any issues with the versions of Python libraries.
