### ISSUE TITLE
AttributeError: 'SetCriterion' object has no attribute 'loss_masks'. Did you mean: 'loss_labels'?

### ISSUE THREAD

**Issue by Glanceyes** [OPPO-Mente-Lab/attention-mask-control#3]
Thanks for your work!

I tried to execute `train_boxnet.sh` and there were some issues with non-existing attribute 'loss_masks'.
Specifically, in `boxnet_models/boxnet.py`, line 199, in `get_loss`

```
def get_loss(self, loss, outputs, targets, indices, num_boxes, **kwargs):
        loss_map = {
            'labels': self.loss_labels,
            'cardinality': self.loss_cardinality,
            'boxes': self.loss_boxes,
            'masks': self.loss_masks
        }
        assert loss in loss_map, f'do you really want to compute {loss} loss?'
        return loss_map[loss](outputs, targets, indices, num_boxes, **kwargs)
```

Looking forward for your reply, Thank you.

**Comment by Wrch1994** [comment]
Hello, we have fixed some bugs in the training code in the latest commit. After testing, this version of the code can be used for training normally. Please pull the latest code in the master branch and set up the environment according to the updated environment.yaml to prevent any issues with the versions of Python libraries.
